### ISSUE TITLE
Translated breadcrumbs (delaying routes init)

### ISSUE THREAD

**Issue by dagi12** [icd2k3/react-router-breadcrumbs-hoc#100]
Is there a way to delay hoc initialization. Currently I do something like this

```
const getTranslatedRoutes = (): BreadcrumbsRoute[] => [
  { path: '/logout', breadcrumb: i18n.t('global.menu.logout') },
  { path: '/main', breadcrumb: i18n.t('global.menu.main') },
  { path: '/admin', breadcrumb: i18n.t('global.menu.admin') }
];

export default connect(
  mapStateToProps,
  null
)(withBreadcrumbs(getTranslatedRoutes())(Breadcrumbs));

```
Which lead to error because app didn't download translations yet. I need route configuration to be lazily initialized.

**Comment by icd2k3** [comment]
@dagi12 check out this [code sandbox](https://codesandbox.io/s/bare-bones-example-ygo7o) it seems to work with localization! Maybe the `connect` HOC is causing you issues...
