### ISSUE TITLE
Unnecessary peer dependency on react-router-dom

### ISSUE THREAD

**Issue by fdc-viktor-luft** [icd2k3/react-router-breadcrumbs-hoc#102]
Please remove the dependency `react-router-dom` completely from your project.

The only import in your source code that points to `react-router-dom` is actually part of `react-router`.

In your tests you can easily replace the imported `NavLink` with an "a" tag. I have a PR ready, but you're currently not allowing to provide PRs.

And please don't forget to remove the corresponding peer dependency in your `package.json`.

**Comment by icd2k3** [comment]
Hey @fdc-viktor-luft, I'll look into it!

PRs should be allowed, you can't submit one?

**Comment by icd2k3** [comment]
Dependency has been removed in `3.2.8`

**Comment by fdc-viktor-luft** [comment]
Maybe I did something wrong when pushing my PR. But your PR looked very similar to mine. The only left differences:

- In your `package.json` you forgot to remove the dev dependency "@types/react-router-dom"
- In your `rollup.config.js` you can remove "react-router-dom" from your `globals`

But nevertheless thank you for your fast response and fix 👍

**Comment by icd2k3** [comment]
Thanks @fdc-viktor-luft! I'll remove those other instances shortly
