### ISSUE TITLE
"//" produces double matches

### ISSUE THREAD

**Issue by slide333333** [icd2k3/react-router-breadcrumbs-hoc#105]
Given the projects sandbox at https://codesandbox.io/s/react-router-breadcrumbs-hoc-demo-iqmx6.
Using a URL with a double slash like "https://iqmx6.csb.app/users//john" is rendered as
`Home>Users>Home>John`  whereas I would expect to render it as just `Home>Users` or maybe `Home>Users>/John` (depending on the configuration).
Not sure if this is somehow the intended behaviour.

**Comment by icd2k3** [comment]
@slide333333 honestly 2 slashes in a URL is just something I didn't consider... it seems pretty edge-casey, but this should be a simple fix on my end. I'll get around to it soon!
