### ISSUE TITLE
define breadcrumb‘s description

### ISSUE THREAD

**Issue by TangTangJia** [icd2k3/react-router-breadcrumbs-hoc#108]
I want to define some  description  like  {path:'/doc',title:'document'}，but  now  i got 
![image](https://user-images.githubusercontent.com/34622385/83003076-6325e380-a040-11ea-86ad-614770bd9124.png)

wthat could I do？thanks!

**Comment by icd2k3** [comment]
@TangTangJia instead of `title` it should be `breadcrumb`:

```
{ path: '/doc', breadcrumb: 'document' }
```

**Comment by TangTangJia** [comment]
> breadcrumb



> @TangTangJia instead of `title` it should be `breadcrumb`:
> 
> ```
> { path: '/doc', breadcrumb: 'document' }
> ```

thanks! I have solved it
