### ISSUE TITLE
Path matching

### ISSUE THREAD

**Issue by ikovic** [icd2k3/react-router-breadcrumbs-hoc#16]
I've ran into a case when path matching didn't follow `react-router` - I've got a few routes set up as this:
```
.../reports
.../reports/:id
.../reports/create
```

When accessing `...reports/create`, router displays the correct page, but the breadcrumb gets a wrong match - breadcrumb returned from HOC matches the `.../reports/:id` path, with `create` as `id` value.

I've patched the problem by changing from `.../reports/:id` to `.../reports/details/:id`.

Thanks for the awesome library, this is the first issue I've had with it. I'll be glad to provide more info if necessary.

**Comment by icd2k3** [comment]
Hey @ikovic after some testing, I think just changing the order of the routes in your route config should work. The package returns the first match it finds in the list, so `/create` matches with `/:id` first (think of it like a switch statement). Changing your config to something like this should work:

```
[
  { path: '/reports', breadcrumb: 'reports' },
  { path: '/reports/create', breadcrumb: 'create'},
  { path: '/reports/:id', breadcrumb: 'id' },
]
```

**Comment by icd2k3** [comment]
Closing this issue, but please re-open if there's still an issue!
