### ISSUE TITLE
Omitting breadcrumb for a path

### ISSUE THREAD

**Issue by m4rk3r** [icd2k3/react-router-breadcrumbs-hoc#18]
Thank you for this elegantly simple library!

Quick question: Sometimes routes don't require a breadcrumb.. would it be more flexible to allow for perhaps a `null` breadcrumb in order to omit it? Right now doing something silly like using `noop` and checking while rendering, but perhaps checking for a present but `null` prop instead of throwing an error could be more forgiving?

**Comment by icd2k3** [comment]
Hey @m4rk3r, just so I'm clear, are you saying you're extending your [react router config](https://reacttraining.com/react-router/web/example/route-config) object with a `breadcrumbs` prop? 

I currently don't use it this way, but I think that is a good idea to support and I could make that change soon!

**Comment by m4rk3r** [comment]
@icd2k3 yep, exactly! Sorry should of included that detail. Works perfectly otherwise. Thanks!

**Comment by icd2k3** [comment]
No worries, and thanks for clarifying - I'll add support for this soon(ish)!

**Comment by icd2k3** [comment]
Hey @m4rk3r this should be supported with version `1.1.2` could you confirm when you have a moment?

**Comment by m4rk3r** [comment]
@icd2k3 Thanks, works great!
