### ISSUE TITLE
Real example

### ISSUE THREAD

**Issue by AngelWayfarer** [icd2k3/react-router-breadcrumbs-hoc#26]
Hi everybody!
Could somebody show a full example of dynamic route with converting userID to "John Doe"?

I can't figure out how to transfer data from axios/redux/anywere to the UserBreadcrumb component...

Thanks for any help

**Comment by icd2k3** [comment]
Hey @AngelWayfarer, using redux it would probably look something like:

UserBreadcrumb.jsx
```js
const PureUserBreadcrumb = ({ firstName }) => <span>{firstName}</span>;

const mapStateToProps = (nextState, nextOwnProps) => ({
  firstName: nextState.userReducer.usersById[nextOwnProps.match.params.id].firstName,
});

export default connect(mapStateToProps)(PureUserBreadcrumb);
```

**Comment by AngelWayfarer** [comment]
Thanks for your answer!! 
I have got the idea.

**Comment by icd2k3** [comment]
Thanks for closing! FWIW I've added a redux match example to the readme https://github.com/icd2k3/react-router-breadcrumbs-hoc/blob/master/README.md#dynamic-breadcrumbs
