### ISSUE TITLE
render "home" breadcrumb

### ISSUE THREAD

**Issue by diegolaciar** [icd2k3/react-router-breadcrumbs-hoc#3]
Hi,

react-router works really good, thanks for publish your project.

Question: How can I do to display the breadcrumb like this ->

home / user / Jonny

Including NavLink to Home page  ?

I' m doing this but not shows the home link.

const routes = [
 { path: '', breadcrumb: 'Home' },
  { path: 'users', breadcrumb: 'Users' },
  { path: 'users/:userId', breadcrumb: UserBreadcrumb},
  { path: 'something-else', breadcrumb: ':)' },
];

OR:   { path: '/', breadcrumb: 'Home' },
Thanks.

**Comment by icd2k3** [comment]
Hey @diegolaciar, thanks for the question!

I'll work on a patch to allow for the home root route in config.

For now, since it's probably expected that the Home breadcrumb would appear everywhere, you could just render one separately outside of the config. Using the readme example:

```js
import React from 'react';
import { NavLink } from 'react-router-dom';
import { withBreadcrumbs } from 'react-router-breadcrumbs-hoc';

const UserBreadcrumb = ({ match }) =>
  <span>{match.params.userId}</span>; // use match param userId to fetch/display user name

const routes = [
  { path: 'users', breadcrumb: 'Users' },
  { path: 'users/:userId', breadcrumb: UserBreadcrumb},
  { path: 'something-else', breadcrumb: ':)' },
];

const Breadcrumbs = ({ breadcrumbs }) => (
  <div>
    <NavLink to="/"}>Home</NavLink>/
    {breadcrumbs.map(({ breadcrumb, path, match }) => (
      <span key={path}>
        <NavLink to={match.url}>
          {breadcrumb}
        </NavLink>
        <span>/</span>
      </span>
    ))}
  </div>
);
```

**Comment by icd2k3** [comment]
@diegolaciar I pushed a new version `1.0.3` to address this. You should now be able to use:

`{ path: '/', breadcrumb: 'Home' }`

In your config. Thanks again, and please let me know if you run into any other issues.

**Comment by diegolaciar** [comment]
@icd2k3 I updated react-router-breadcrumbs-hoc       ^1.0.2  →  ^1.0.3

I tried again using :

```{ path: '/', breadcrumb: 'Home' }```
 or
```{ path: '', breadcrumb: 'Home' }```

and i don´t get the home breadcrumb.

**Comment by diegolaciar** [comment]
Looking into code could be something with my routes config. 

All my routes are child from home route. 

I can' t discover whats going on.

Anyway, thank you for you fix and fast response !

**Comment by icd2k3** [comment]
Thanks @diegolaciar - reopening the issue because I was able to find some unexpected behavior for the "home" "/" route on my end as well.

**Comment by icd2k3** [comment]
@diegolaciar my apologies, there was a problem with the compiled build published to npm (apparently `prepublishOnly` doesn't work as I expected it to)

...anyways, this problem will be solved after upgrading to `1.0.5`

Sorry for the inconvenience - please let me know if it solves the issue on your end as well

**Comment by diegolaciar** [comment]
Hi @icd2k3,

I just updated react-router-breadcrumbs-hoc ^1.0.3 → ^1.0.5 and installed the pkg.

I have on the config

{ path: `/`, breadcrumb: "Home" },
 { path: ``, breadcrumb: "Home" },

It looks like the issue persist.
Breadcrumbs render good and it shows all the routes I configured, but is not showing the "home" breadcrumb.

**Comment by diegolaciar** [comment]
If I do 
```{ path: "", breadcrumb: "Home" },```
Error: withBreadcrumbs: `breadcrumb` and `path` must be provided in every route object

So I just leave ```{ path: "/", breadcrumb: "Home" },```

**Comment by icd2k3** [comment]
`{ path: "/", breadcrumb: "Home" }` should work (the path can't be blank).

Seems to be working OK on my end... Could you please provide the `react`, `react-router`, & `react-router-dom` versions you're using?

**Comment by diegolaciar** [comment]
"react": "^16.1.0",
"react-dom": "^16.1.0",
"react-router": "^4.2.0",

I cant push all the code but looks something like this.
```javascript
import React, { Component } from "react";
import PropTypes from "prop-types";
import { withBreadcrumbs } from "react-router-breadcrumbs-hoc";
import NavigateNext from "material-ui-icons/NavigateNext";
import { Link, NavLink } from "react-router-dom";

const routes = [
  { path: "/", breadcrumb: "Home" },  
  { path: "/users", breadcrumb: "Users" },
];
export class App extends Component {
  static propTypes = {
    children: PropTypes.node,
  };

  static defaultProps = {
    children: "No content.",
  };

  render() {
    const { breadcrumbs } = this.props;
    return (
      <div className="home-app">
        <div className="page-container">
          <Header />
          <div>
            {breadcrumbs.map(({ breadcrumb, path, match }, index) => (
              <span key={path}>
                {index < breadcrumbs.length - 1 ? (
                  <NavLink to={match.url}>{breadcrumb}</NavLink>
                ) : (
                  breadcrumb
                )}
                {!!(index < breadcrumbs.length - 1) && (
                  <span
                    style={{
                      verticalAlign: "sub",
                    }}
                  >
                    <NavigateNext
                      style={{
                        width: 16,
                        height: 16,
                      }}
                    />
                  </span>
                )}
              </span>
            ))}
          </div>
          {this.props.children}
        </div>
      </div>
    );
  }
}

App = withBreadcrumbs(routes)(App);
export default App;

```

**Comment by diegolaciar** [comment]
@icd2k3,

Your fix is working. 

I cleared node_modules folder.  Looks like it was caching the older version.

Thank you

**Comment by icd2k3** [comment]
@diegolaciar thank you!

Oddly, I still can not repro this issue in v`1.0.5` 😞  in my project:
![img](https://www.dropbox.com/s/39uwq45n4cr5z3e/Screenshot%202017-11-10%2008.28.59.png?raw=1)

My plan is to (hopefully) get a demo environment up and running this weekend which might be a good way to test different theories in isolation.

Until we figure out what might be going wrong on your end, would my first suggestion [here](https://github.com/icd2k3/react-router-breadcrumbs-hoc/issues/3#issuecomment-342619839)  work in the meantime?

**Comment by icd2k3** [comment]
@diegolaciar good to hear! Please let me know if you run into any other issues.
