### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by 9renpoto** [icd2k3/react-router-breadcrumbs-hoc#32]
🙏

**Comment by icd2k3** [comment]
Hey @9renpoto!

I must admit, I don't use TypeScript very often. Could you please elaborate what the issue with TypeScript is?

Of course, I'd like this package to be as flexible as possible!

**Comment by icd2k3** [comment]
@9renpoto could you elaborate on what the issue is with TypeScript?

Also happy to take a look at a PR if you know the issue and how to fix it.

Thanks!
