### ISSUE TITLE
breadcrumb prop is being ignored.

### ISSUE THREAD

**Issue by Pixelatex** [icd2k3/react-router-breadcrumbs-hoc#41]
My route looks like this:

```
{
    path: '/careers/:id',
    exact: true,
    breadcrumb: 'test',
    component: CareerDetail
  },
```

My breadcrumb component:

```
 <div className="breadcrumbs">
      {breadcrumbs.map((breadcrumb, index) => (
          <span
            className="breadcrumbs__item"
            key={`${breadcrumb.key}-${index}`}>
            <NavLink to={breadcrumb.props.match.url}>{breadcrumb}</NavLink>
          </span>
      ))}
    </div>
```

The url I navigate to:
`http://localhost:3000/careers/5b71927e3e07c3430900118c
`
What I expect to see in the props:
`careers > test
`
What I see:
`careers > 5b71927e3e07c3430900118c`

Am I missing something?

**Comment by icd2k3** [comment]
Hey @Pixelatex,

That should work. Could you post your whole route/breadcrumb config array when you have a moment?

Thanks

**Comment by Pixelatex** [comment]
Got it work by moving the breadcrumb under the path like this:

```
{
    path: '/careers/:id',
    exact: true,
    breadcrumb: 'test',
    component: CareerDetail
  },
```

No idea why this is an issue though, really weird bug

**Comment by icd2k3** [comment]
Strange! Did the order of the route config objects change by chance? The HOC will return the first match, so order can affect how the breadcrumbs are generated: https://github.com/icd2k3/react-router-breadcrumbs-hoc#order-matters

**Comment by Pixelatex** [comment]
the order of the route objects wasn't an issue, I tried this on a few other routes and it also had the same issue somehow

**Comment by icd2k3** [comment]
Thanks for the follow-up @Pixelatex!

I adjusted some unit tests to see if I could repro the issue, but so far no dice! When you have a moment, would you be able to post your entire route array? It may help in tracking down the problem.

**Comment by icd2k3** [comment]
Hey @pimmey, thanks for reporting and apologies for the issue. I'm re-opening this thread and I'll try to come up with a repro case tonight!

**Comment by icd2k3** [comment]
@pimmey I set up a quick code sandbox with your route config and it _seems_ to be working alright... maybe something else is causing the issue? 🤔

https://codesandbox.io/s/pknr4kyll0

**Comment by pimmey** [comment]
@icd2k3 I see why it didn't work now - it wasn't clear to me that `routesConfig` has to be passed to `withBreadcrumbs()` 🙂thought it should happen automatically or something. Anyway, this should do it, works fine.

**Comment by icd2k3** [comment]
Ohh, I could do a better job of calling that out in the readme... added a small change [here](https://github.com/icd2k3/react-router-breadcrumbs-hoc#already-using-a-route-config-array-with-react-router).

Thanks @pimmey!
