### ISSUE TITLE
How to forward extra props from routes to breadcrumbs?

### ISSUE THREAD

**Issue by taschetto** [icd2k3/react-router-breadcrumbs-hoc#48]
Hi! I love this package. So simple and yet so powerful. Congratulations.

I'd like to forward some props from my `routes` array in order to create a responsive breadcrumb. Something like this:

```
const routes = [
  { path: '/', breadcrumb: null },
  { path: '/app', breadcrumb: null },
  { path: '/app/hello', breadcrumb: 'hello', mobile: true },
  { path: '/app/world', breadcrumb: 'world', mobile: true },
]
```

It'd be great to have use it to filter out breacrumbs that are not suitable for a mobile screen.

```
const Breadcrumb = ({ breadcrumbs, mobileScreen }) => {

  const toDisplay = mobileScreen
    ? breadcrumbs.filter(b => b.props.mobile)
    : breadcrumbs

  return (
    <Toolbar>
      {toDisplay.map((breadcrumb, index) => {
        return (
          <React.Fragment key={breadcrumb.key}>
            <Button
              component={Link}
              to={breadcrumb.props.match.url}>
              {breadcrumb}
            </Button>
            {index < breadcrumbs.length - 1 && '/' />}
          </React.Fragment>
        )
      })}
    </Toolbar>
  )
}
```

It is possible? I've tried to inspect the `breadcrumb` object without success.

**Comment by taschetto** [comment]
I don't think I have the skills to create this PR, but I'll take it as a holliday challenge. :)

**Comment by icd2k3** [comment]
Just a thought - In the meantime, for this specific issue, you could switch to using component breadcrumbs with a class that hides at mobile breakpoints:

`{ path: '/app/hello', breadcrumb: () => <span className="hide-mobile">Hello</span>, mobile: true },`
