### ISSUE TITLE
How to match 404 page?

### ISSUE THREAD

**Issue by Sven65** [icd2k3/react-router-breadcrumbs-hoc#50]
In my application, I've got a catch-all route for 404 pages, `<Route component={Page404} />` and I'm wondering how I would use this HOC for a custom breadcrumb with the 404 page without having to define all of my routes in the `withBreadcrumbs` function.

Is this even possible?

**Comment by icd2k3** [comment]
Hey @Sven65,

Currently this isn't supported, but it probably should be! I'll look into implementing this in the near future...

In the meantime, you could potentially do a custom solution by using `withRouter` from react-router and rendering an additional breadcrumb if the `match` is null.

**Comment by icd2k3** [comment]
This turned out to be easier than I originally thought (pretty sure this PR above will cover it... at least all the tests are passing)

**Comment by Sven65** [comment]
I'll check it out tomorrow, thanks!

**Comment by Sven65** [comment]
Alright, I had a look at it and I found some issues.

Using the demo shown here, I get these breadcrumbs:

| Route             | Breadcrumb                             |
|-------------------|----------------------------------------|
| /applications/:id | Home / Applications / Edit Application |
| /applications     | Home / 404                             |
| /admin            | Home / 404                             |
| /admin/apps       | Home / Admin / 404                     |
| /admin/apps/:id   | Home / Admin / Apps / 404              |
| /privacy          | Home / 404                             |
| /terms            | Home / 404                             |

```jsx
import withBreadcrumbs from 'react-router-breadcrumbs-hoc'

import React from 'react'

import { Link } from 'react-router-dom'


const breadcrumbRoutes = [
	{ path: '/applications/:id', breadcrumb: 'Edit Application' },
	{ path: '/admin/apps/:id', breadcrumb: 'Edit Application' },
	{ path: '/privacy', breadcrumb: 'Privacy Policy' },
	{ path: '/terms', breadcrumb: 'Terms of Service' },
]

const BreadcrumbDemo = ({
	breadcrumbs,
}) => (
	<div>
		{
			breadcrumbs.map(crumb => (
				<span key={crumb.key}>
					<Link to={crumb.props.match.url}>
						{ crumb.props.children }
					</Link>
				</span>
			))
		}
	</div>
)

export default withBreadcrumbs(breadcrumbRoutes, {
	routeNotFoundBreadcrumb: '404',
})(BreadcrumbDemo)
```

As for my routes, these are the ones I have.

```jsx
<Switch>
	<Route path="/" exact component={Home} />
	<Route path="/oauth" component={OAuth} />
	<Route path="/applications" component={Dash} />
	<Route path="/applications/:id" exact component={Dash} />
	<Route path="/docs" component={Docs} />
	<Route path="(/privacy|/terms)" exact component={Legal} />
	<Route path="/admin(|/|/apps|/users)" exact component={Admin} />
	<Route path="/admin/apps/:id" exact component={Admin} />
	<Route component={Page404} />
</Switch>
```

**Comment by icd2k3** [comment]
Thanks for having a look!

Arg, yea, seems like this is a bit more complex than I originally thought... Back to the drawing board! In the meantime, there might be some way to leverage withRouter (not sure if it knows about 404 routes or not 🤔).

**Comment by icd2k3** [comment]
Alright, did some more investigating... The main problem is this HOC is unaware of the routes you might have set upstream, so determining which routes are 404 doesn't seem possible AFAIK.

My PR _would_ work, but only _if_ you have all your routes defined when they're passed into the HOC. Therefore I'll be closing the PR and suggesting workarounds unless anyone has a good idea how to support it.

This is a bit hacky, but if I were to solve this use-case without a change to this HOC I would probably do it through a css class:

Breadcrumbs.jsx
```js
<div>
  {
    breadcrumbs.map(crumb => (
      <span key={crumb.key}>
        <Link to={crumb.props.match.url}>
          { crumb.props.children }
        </Link>
      </span>
    ))
  }
  <span className="route-not-found-breadcrumb">404</span>
</div>
```

Page404.jsx
```js
// ...
  componentDidMount() {
    body.classList.add('is-404');
  }
// ...
```

Breadcrumbs.css
```css
.route-not-found-breadcrumb { display: none; }
body.is-404 .route-not-found-breadcrumb { display: inline-block; }
```

If anyone has ideas about how to support this functionality in _this_ HOC, I'm all ears! Again, the main issue is that I don't see a good way of checking which routes the user has defined upstream.

**Comment by icd2k3** [comment]
Closing this because it is over a year old, and has a workaround documented.
