### ISSUE TITLE
Handle multiple params

### ISSUE THREAD

**Issue by birendra-90** [icd2k3/react-router-breadcrumbs-hoc#52]
How to handle multiple params?

e.g. /products/:productId/categories/:categoryId

**Comment by icd2k3** [comment]
Hi @birendra-90 👋 

This is supported. With defaults enabled you could do something like this:

```js
const routes = [
  { path: '/products/:productId', breadcrumb: ({ match }) => <span>{match.params.productId}</span> },
  { path: '/products/:productId/categories/:categoryId', breadcrumb: ({ match }) => <span>{match.params.categoryId}</span> },
];

withBreadcrumbs(routes)(MyComponent)
```

For the above, if the URL is `/products/1/categories/2` it will produce breadcrumbs `Home / Products / 1 / Categories / 2`

This will work with default breadcrumbs option [disabled](https://github.com/icd2k3/react-router-breadcrumbs-hoc#disabling-default-breadcrumbs-for-paths) too. You'd just have to define route breadcrumbs for 'products' and 'categories'.

Hope that helps!
