### ISSUE TITLE
How to hide Parent when child route is active

### ISSUE THREAD

**Issue by Shubham-Sinha** [icd2k3/react-router-breadcrumbs-hoc#53]
Hi, 

I tried to implement React Router example. Here's the [codesandbox]( https://codesandbox.io/s/912165259w) link.

[![Screenshot-2019-01-24-at-12-58-34-PM.png](https://i.postimg.cc/WbG4TJ17/Screenshot-2019-01-24-at-12-58-34-PM.png)](https://postimg.cc/56tJmyvH)

The links at top is the breadcrumb 

The links to ``Bus`` and ``Cart`` at bottom is present on the parent route ``Tacos`` but is visible on child route ``Bus`` or ``Cart``

**Comment by icd2k3** [comment]
Hi @Shubham-Fareye,

Just so I understand: do you expect...

1.) tacos to be removed from the breadcrumbs like this?
![image](https://user-images.githubusercontent.com/1458959/51707912-49513800-1fd7-11e9-9235-e6c5f31ebcab.png)

Or

2.) that `BusCart` links shouldn't be there like this?
![image](https://user-images.githubusercontent.com/1458959/51707996-8caba680-1fd7-11e9-9c26-e8eaaf2c954f.png)

#1 can be solved using this module
#2 can be solved by refactoring your routes in react-router

**Comment by icd2k3** [comment]
Closing this after 2 weeks of inactivity. Happy to re-open and help when the problem is clarified!

**Comment by pjvds** [comment]
@icd2k3 I would love to see an example of scenario one :)

**Comment by icd2k3** [comment]
@pjvds it's a bit verbose, but since `location` is passed to dynamic breadcrumbs, we can use that to determine wether or not to show "Tacos"

```js
const routes = [
  {
    path: "/tacos",
    breadcrumb: ({ location: { pathname } }) =>
      pathname.toLowerCase() === "/tacos" ? "Tacos" : null
  },
```

Here's a [codesandbox](https://codesandbox.io/s/bare-bones-example-5ntrl)

![gif](https://www.dropbox.com/s/cl9iejggawbwr9u/jul-19-2019%2014-15-57.gif?raw=1)

**Comment by pjvds** [comment]
Thanks @icd2k3 for the fast and prompt answer ❤️
