### ISSUE TITLE
Please help with this code base.

### ISSUE THREAD

**Issue by amitkumarsingh** [icd2k3/react-router-breadcrumbs-hoc#55]
I am unable to read the breadcrumb props.
What am i missing ?
```
import BreadCrumb from '../../../../components/bread-crumb';
import {scenarioManagerRoutes} from '../../routes';
class ScenarioManagerHome extends React.PureComponent<Props, State> {
render() {
		const scenarioModelList = this.props.scenarioModels.data;
		const breadcrumbs = this.props; // unable to read props
}
}

export default withBreadcrumbs(scenarioManagerRoutes)(ScenarioManagerHome);

const _ScenarioManagerHome = connect(
	(state) => ({
		isLoading: state.scenarioManager.isLoading,
	}),
	(dispatch) =>
		bindActionCreators(
			{ stopScenarioFlow },
			dispatch,
		),
)(ScenarioManagerHome);

export { _ScenarioManagerHome as ScenarioManagerHome };
```

**Comment by icd2k3** [comment]
👋 hi @amitkumarsingh . At first glance, you'd want to change:

`const breadcrumbs = this.props;` to `const { breadcrumbs } = this.props;`

If that's not the issue, I'd have to see what's in `scenarioManagerRoutes` to be able to assist

**Comment by amitkumarsingh** [comment]
I tried with what you have mentioned but it's undefined.

In my scenario manager there are array of routes as mentioned in code
sample.

**Comment by icd2k3** [comment]
If you try using the HOC without pre-defined routes does it work?
`withBreadcrumbs()(ScenarioManagerHome)`
The HOC will attempt generate breadcrumbs for you if no routes are provided.

**Comment by amitkumarsingh** [comment]
```
export const scenarioManagerRoutes = [
	{ path: '/scenario/home', component: ScenarioManagerHome, exact: true , breadcrumb : 'Scenario'},
	{ path: '/scenario/model/create', component: ScenarioModelComposer, exact: true , breadcrumb : 'Create Scenario'},
	{ path: '/scenario/model/create/:id?', component: ScenarioModelComposer, exact: true , breadcrumb : 'Edit Scenario'},
	{ path: '/scenario/model/details/:id?', component: ScenarioModelDetails, exact: true , breadcrumb : 'Scenario Details'},
```

**Comment by amitkumarsingh** [comment]
> If you try using the HOC without pre-defined routes does it work?
> 
> `withBreadcrumbs()(ScenarioManagerHome)`
> 
> The HOC will attempt generate breadcrumbs for you if no routes are provided.

Nope.

**Comment by amitkumarsingh** [comment]
Is there something i am missing ? As per documentaion i have used it correctly ?

**Comment by icd2k3** [comment]
At first glance the code looks ok, but remotely debugging can be tricky sometimes... I can tell you this HOC has test coverage to ensure it works, but something about your codebase/setup/config etc may be affecting it.

Couple more things:

1.) which version of this component are you using? (2.3.1?)
2.) any errors in console?
3.) when running the HOC w/o route config `withBreadcrumbs()(ScenarioManagerHome)`. What does `console.log(this.props.breadcrumbs)` output?
4.) I assume `withBreadcrumbs()(ScenarioManagerHome)` is being mounted somewhere? (not the `connect`-wrapped version)

**Comment by icd2k3** [comment]
OH, also, which version of `react-router` are you using?

**Comment by amitkumarsingh** [comment]
1.) which version of this component are you using? (2.3.1?)  **YES**
2.) any errors in console? **NO**
3.) when running the HOC w/o route config withBreadcrumbs()(ScenarioManagerHome). What does console.log(this.props.breadcrumbs) output? **undefined**
4.) I assume withBreadcrumbs()(ScenarioManagerHome) is being mounted somewhere? (not the connect-wrapped version) **I did not understand this**
5) **"react-router-dom": "^4.2.2",**

**Comment by icd2k3** [comment]
Ok, I'm using 4.3.1, but it shouldn't make a difference... Something else you could try is copying the [example component](https://github.com/icd2k3/react-router-breadcrumbs-hoc#example) directly into a _new_ component in your codebase and mounting it somewhere. This would rule out any possible issues with your component.

**Comment by amitkumarsingh** [comment]
My app js code.

```

class _App extends React.Component<Props> {
	render() {
		return (
			<Provider store={store}>
				<BrowserRouter>
					<Bootstrap>
						<Switch>
							{routes.map((item, index) => {
								return (
									<SensemakerRoute
										key={index}
										path={item.path}
										exact={item.exact}
										component={item.component}
										store={store}
									/>
								);
							})}
						</Switch>
					</Bootstrap>
				</BrowserRouter>
			</Provider>
		);
	}
}

export const App = _App;
```

**Comment by amitkumarsingh** [comment]
<Bootstrap> is my another HOC. I have tried but eventually could not get the breadcrumbs up and running.

**Comment by amitkumarsingh** [comment]
Fixed this issue. Closing it.
