### ISSUE TITLE
Need help in route config

### ISSUE THREAD

**Issue by amitkumarsingh** [icd2k3/react-router-breadcrumbs-hoc#58]
When i go to route ```/scenario/edit/:id``` I need breadscrumb as Home/scenario/editwithid currently getting edit scenario twice.

```
export const scenarioManagerRoutes = [
	{ path: '/scenario/', component: ScenarioManagerHome, exact: true, breadcrumb: ()=> <React.Fragment><MyIcon class="icon-flow-tree"/>Scenario</React.Fragment>},
	{ path: '/scenario/create', component: ScenarioModelComposer, exact: true, breadcrumb: ()=> <React.Fragment><MyIcon class="icon-file2"/>Create Scenario</React.Fragment> },
	{ path: '/scenario/edit/:id?', component: ScenarioModelComposer, exact: true, breadcrumb: 'Edit Scenario', },
	{ path: '/scenario/details/:id?', component: ScenarioModelDetails, exact: true, breadcrumb: 'Scenario Details', },
];
```

Also if my route is ```/admin/apps/list``` I just want bread crumb as home/admin/list. How do i acheive this ?

**Comment by icd2k3** [comment]
> When i go to route /scenario/edit/:id I need breadscrumb as Home/scenario/editwithid currently getting edit scenario twice.

By default, this HOC will attempt to create breadcrumbs for you. What you probably want to do is [disable the default](https://github.com/icd2k3/react-router-breadcrumbs-hoc#disabling-default-breadcrumbs-for-paths) for this specific path. The 3rd option would probably work well for this case:
`withBreadcrumbs(routes, { excludePaths: ['/scenario/edit'] })`

> Also if my route is /admin/apps/list I just want bread crumb as home/admin/list. How do i acheive this ?

Same kinda solution as above, you should be able to disable the default breadcrumb for /admin/apps/list

**Comment by icd2k3** [comment]
@amitkumarsingh here's a codesandbox of what you're describing (I think) https://codesandbox.io/s/k9p8k65pov

Note, in `components/Breadcrumbs` I'm using `excludePaths: ["/scenario"]` to avoid generating a default breadcrumb for this _specific_ path section. Then, only the breadcrumbs for edit, create, and details will render.

**Comment by amitkumarsingh** [comment]
Does not solve the purpose though. 
Say i have route as

```
{ path: '/scenario/edit/:id?', component: ScenarioModelComposer, exact: true, breadcrumb: 'Edit Scenario', },
{ path: '/scenario/details/:id?', component: ScenarioModelDetails, exact: true, breadcrumb: 'Scenario Details', },
```
Then i want my breadcrumb as `home > scenario > edit scenario` but currently am getting `home > scenario > edit scenario > edit scenario` 
How to solve this ?

**Comment by icd2k3** [comment]
@amitkumarsingh alright, this is the same codesandbox, just without the excludePaths option. Seems to be working as expected?

**Comment by icd2k3** [comment]
Oh, I think I know what might be going on! Does the double breadcrumb show up only when the `id` in the param is set? Let me update the codesandbox to show you how to get around that

**Comment by icd2k3** [comment]
Oops, didn't mean to close the issue there 😬. I think I just realized what might be going on... you're seeing the double generated breadcrumbs only _when_ the `id` param is present right? There's a couple ways around this:

- Quick fix: use the `excludePaths` option to only generate a breadcrumb for the `id` routes. Updated codepen: https://codesandbox.io/s/o9z4vz5l26
- Longer, cleaner fix: disable default-gerated breadcrumbs entirely and _only_ use the ones provided in your route config

**Comment by amitkumarsingh** [comment]
My App.js code is this.

```
<Provider store={store}>
				<BrowserRouter>
					<Bootstrap>
						<Switch>
							{routes.map((item, index) => {
								return (
									<SensemakerRoute
										key={index}
										path={item.path}
										exact={item.exact}
										component={item.component}
										store={store}
										routes={item.routes}
									/>
								);
							})}
						</Switch>
					</Bootstrap>
				</BrowserRouter>
			</Provider>
```

And my sensemaker code is this. Where am mounting the breadcrumb HOC and passing the breadcrumb as props ? 

```
const SensemakerRoute = ({ component: Component, store, ...rest }: any) => {
	return (
		<Route
			{...rest}
			render={(props) => {
				return isAuthenticated(store, props) ? (
					<Component {...props} breadcrumbs={rest.breadcrumbs} />
				) : (
					<Redirect to="/home" />
				);
			}}
		/>
	);
};

export default withBreadcrumbs(routes ,{
	disableDefaults: true,
})(SensemakerRoute);
```
But in your case your are mounting HOC on breadcrumb component itself ? Not working for me.

**Comment by icd2k3** [comment]
It shouldn't matter where it is mounted as long as it is somewhere within a react-router Router component. Either codesandbox link above should fix the issue for you. Make sure to check `components/Breadcrumbs` and `modules/routeConfig` in each. The excludePaths option should be easier to implement!

**Comment by amitkumarsingh** [comment]
It worked. Thanks :+1:
