### ISSUE TITLE
Issues with React.memo

### ISSUE THREAD

**Issue by bhollis** [icd2k3/react-router-breadcrumbs-hoc#66]
When a component is passed in as the `breadcrumb` property of a route, and that component is wrapped with `React.memo` (such as any component using React-Redux v7), this library blows up with "Objects are not valid as a React child".

I think there's a `react-is` library which may be helpful in detecting these components and handling them correctly.

**Comment by icd2k3** [comment]
Thanks for reporting @bhollis!

I agree, this module should support the `React.memo` use-case. I should have some time in the near future to look into supporting this.

**Comment by icd2k3** [comment]
@bhollis this should work as of the latest version `3.2.0`. Let me know if you run into any issues!
