### ISSUE TITLE
Please use yarn to install dependencies, not npm

### ISSUE THREAD

**Issue by polomoshnov** [icd2k3/react-router-breadcrumbs-hoc#74]
You suggest to use `npm install react-router-breadcrumbs-hoc --save` in the README file but the preinstall script in package.json throws an error with the following message: `Please use yarn to install dependencies, not npm`.

BTW, I'm wondering why there's such a requirement?

**Comment by icd2k3** [comment]
@polomoshnov Oops, this was only supposed to trigger for local development! I didn't realize it was throwing for installing the module itself. I'll remove it right away

**Comment by icd2k3** [comment]
@polomoshnov This is fixed as of v `3.2.2` sorry for the inconvenience and thanks for reporting!

**Comment by polomoshnov** [comment]
No problem! Thank you for all your work on this HOC!
