### ISSUE TITLE
Suppress autmatically added Home Breadcrumb

### ISSUE THREAD

**Issue by mariolegnini** [icd2k3/react-router-breadcrumbs-hoc#76]
Hi, Quick question... is there any way to suppress showing the automatic Home Breadcrumb? Thanks.

**Comment by icd2k3** [comment]
hi @mariolegnini, yep there are a [couple ways](https://github.com/icd2k3/react-router-breadcrumbs-hoc#disabling-default-generated-breadcrumbs) to do this actually!

You can pass null in the route config object
`{ path: '/', breadcrumb: null }`

Or you can use the `excludePaths` option
`withBreadcrumbs(routes, { excludePaths: ['/'] })`

**Comment by mariolegnini** [comment]
Thanks for the super fast response it's appreciated! It Works.
