### ISSUE TITLE
Question about type definition

### ISSUE THREAD

**Issue by darewreck54** [icd2k3/react-router-breadcrumbs-hoc#78]
How would you properly typedef the props that go into the following example you displayed below?

I notice that your just doing a decomposition, but I want to pass in as props.

```
import withBreadcrumbs from 'react-router-breadcrumbs-hoc';

const Breadcrumbs = ({ breadcrumbs }) => (
  <React.Fragment>
    {breadcrumbs.map(({ breadcrumb }) => breadcrumb)}
  </React.Fragment>
)

export default withBreadcrumbs()(Breadcrumbs);

```

So this instead
```
import withBreadcrumbs from 'react-router-breadcrumbs-hoc';

const Breadcrumbs = (props: any) => (
  <React.Fragment>
    {props.breadcrumbs.map(({ breadcrumb }) => breadcrumb)}
  </React.Fragment>
)

export default withBreadcrumbs()(Breadcrumbs);

```

I can't figure out what the any would be from the type definition. 

Same question for 

` 
breadcrumb: String|Function? // if not provided, a default breadcrumb will be returned
 `

For the Function, what is the type of the parameters of the function being passed in

Thanks,
Derek

**Comment by jeanverster** [comment]
Hi @darewreck54, if you have a look at the types defined in the `.d.ts` file you can infer the types.. You would end up with something like this:

`
import withBreadcrumbs, { BreadcrumbsProps } from 'react-router-breadcrumbs-hoc'

type Props = {
  breadcrumbs: BreadcrumbsProps<unknown>[]
  // ...insert other props here
}

const Breadcrumbs: React.FC<Props> = ({ breadcrumbs }) => {
  return (
    <div className="breadcrumbs">
      {breadcrumbs.map(({ breadcrumb, match }, index) => (
        <div className="bc" key={match.url}>
          <Link to={match.url || ''}>{breadcrumb}</Link>
          {index < breadcrumbs.length - 1 && '>'}
        </div>
      ))}
    </div>
  )
}

export default withBreadcrumbs(ROUTES)(Breadcrumbs)
`

let me know if that helps :)

**Comment by icd2k3** [comment]
Thanks for your answer @jeanverster. Closing this for now, but will re-open if more type questions come in!
