### ISSUE TITLE
typescript definition mistake 

### ISSUE THREAD

**Issue by elishas** [icd2k3/react-router-breadcrumbs-hoc#81]
export default function withBreadcrumbs<P>(
  routes: BreadcrumbsRoute[],
  options?: Options
): withRouter<InjectedProps<P>>;

should be:

export default function withBreadcrumbs<P>(
  routes?: BreadcrumbsRoute[],
  options?: Options
): withRouter<InjectedProps<P>>;

routes should be optional

**Comment by icd2k3** [comment]
@elishas thanks for reporting! This has been fixed as of `3.2.4`
