### ISSUE TITLE
How do I add in between crumbs ?

### ISSUE THREAD

**Issue by udielenberg** [icd2k3/react-router-breadcrumbs-hoc#90]
Hey! 

I currently work with `{ disabledDefaults: true }`.

this is a route I have:

```typescript
const routes = [
   { 
       path: '/p/:projectId/environments/:environmentId' , 
       breadcrumb: ({ match }) => { ... return <span>{match.params[...]}</span>} },
   ...
]
```

Is there a way I could get this breadcrumb `${projectId} >  Environments > ${environmentId}`

**Comment by icd2k3** [comment]
@udielenberg yes that is possible. `projectId` and `environmentId` will both be in the `match` object. So, you could do something like this:

```js
const routes = [
  {
    path: '/p/:projectId/environments/:environmentId',
    breadcrumb: ({ match }) => (
      <span>
        {match.params.projectId} > Environments > {match.params.environmentId}
      </span>
    ),
  }
]
```

**Comment by udielenberg** [comment]
thank you ! :)

I over complicated it ✋
