### ISSUE TITLE
Question: Is there a way to not export the current page in breadcrumbs

### ISSUE THREAD

**Issue by StuartMorris0** [icd2k3/react-router-breadcrumbs-hoc#91]
Hello,

Is there a way to not export the current page breadcrumb?

I.e. we have a page like /test/user (you'd be on the User Page).
The current setup exports:
Home > Test > User

Is it possible to only export Home > Test

I cannot just set the User breadcrumb to null as we'd like the same to occur when on the Test Page. The test page would currently export:
Home > Test

We'd only like 'Home' to show for that page.

**Comment by icd2k3** [comment]
Hi @StuartMorris0, there's nothing in the API for this use-case, but I'd recommend just not showing the very last breadcrumb component while mapping over them... something like:

```js
{breadcrumbs.map(({
      match,
      breadcrumb
    }, index) => {
      if (index <= breadcrumbs.length - 1) { return null }
      return ...  // breadcrumb here
    })}
```

**Comment by StuartMorris0** [comment]
Thanks @icd2k3
