### ISSUE TITLE
Question: breadcrumbs propTypes

### ISSUE THREAD

**Issue by StuartMorris0** [icd2k3/react-router-breadcrumbs-hoc#92]
Hello,

Could you share what the {breadcrumbs} propTypes are please? I'm using a strict eslint project which requires PropTypes to be declared. 

I can see it is an array, but do you know what the inner object layout for breadcrumbs are? 

Thanks

**Comment by icd2k3** [comment]
Hi @StuartMorris0,

```
breadcrumbs: PropTypes.shape({
  breadcrumb: PropTypes.node,
  match: // see https://reacttraining.com/react-router/web/api/match
  location: // see https://reacttraining.com/react-router/web/api/location
})
```
