### ISSUE TITLE
How to remove "-" from titles

### ISSUE THREAD

**Issue by arsistyle** [icd2k3/react-router-breadcrumbs-hoc#96]
I am getting some items from an API and the titles of the pages are left with the "-" that comes from the slug.
Can custom names be passed to it in "Route" component?

Example:

```
<Route path="/items/:id" title="Custom name" />
```

**Comment by icd2k3** [comment]
@arsistyle this module does not interact with the title prop on routes

**Comment by arsistyle** [comment]
@icd2k3 
I need the original name, from which it comes from the API.
Is there a way to pass it as a parameter to "Routes"?
as in the example.

**Comment by icd2k3** [comment]
I'm not sure what you're trying to do. the Route component from react-router does _not_ accept `title` as a property at all: https://reacttraining.com/react-router/web/api/Route

If you're trying to set the _breadcrumb_ to "Custom name" then you can just define a `breadcrumb` prop to pass to `react-router-breadcrumbs-hoc` like in the [advanced example](https://github.com/icd2k3/react-router-breadcrumbs-hoc#advanced)
