### ISSUE TITLE
react-router v6

### ISSUE THREAD

**Issue by bravo-kernel** [icd2k3/react-router-breadcrumbs-hoc#97]
Hi, I was just trying this with react-router v6 and it seems that v6 does not export `matchPath` (breaking the breadcrumbs throwing an error).

The readme only states v4 and v5 so I can imagine that this is not yet supported. If this is not an error on my behalf... do you plan to support v6?

**Comment by icd2k3** [comment]
Hey @bravo-kernel I plan to support v6, but it is currently still in alpha. Once it is officially released I’ll look into what changes need to be made here to support it.

**Comment by bravo-kernel** [comment]
@icd2k3 thanks for the quick reply, much appreciated !

**Comment by ajit-wearingo** [comment]
@icd2k3 is it released officially now ?

**Comment by icd2k3** [comment]
yep, but this HOC will only support v5. If you want to use v6 then please use the hook [use-react-router-breadcrumbs](https://github.com/icd2k3/use-react-router-breadcrumbs) instead
